language:
- python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: gIkQh6ROs/ipp9mSLfWGV1Kc690ACsbwLywAXjZAUDc44PM/IMjrb7GEF1juQ7sG7wyvPfE0r013hyxAXXrCwXF4ZvcUB9Qe55hAozT052lbVM1wcAOCzQseSfuhZiy+Wg6cw+UfsgV+AqUQxBLp6VL0OoEXY6U6kGhJG8OVK4b436CzvPea2Ri4llqRdluZ7QNesf6lLut3N+QrsB+gb/R5aDzcJz2G4etq5RvC7znbXg+hsvjzb+1w25HKVPfgdRRWkiOkUS4K8kv8JbuBVgY9K5LGebVHaAxy0O3WXfAMYHspH7ALzyHwZ6iPSEJyUcS5mQThnyrtU+UZfnj3s/Jp03KbgUfavH42BIfHKXb1jOoNNnoPLs6tgtBLKCRdukgX+D2oRsJPrMAmZBjc6+0A+ZIzMrbSt1k9Mh8cyMnHw1erL6FtLXwuxlR0PO40AkIlXKcrHGemBvPxBMlgrRPdTC4HfTijXzGzit4/BJFAY7BHAndENxMKDW/GcsJlgFWjGzVjOwwnPdfAf8Twtxie37uEQIVkSLcducUHKVzIUwj9eeKoJx5pLxwUpNiaGyjd6fp/cr38wFdwntz3Zz5871XEvP07E3kXsxjck0z7Q4n3A/Y41+WEDhMEuPlgdiOPM3FDXLt7O+EI3B4gwsbw/Hh+UPTRN/xhOrc3C2U=
  app: zuzhi-flasktaskr
  on:
    branch: master
    python: 3.6
    repo: zuzhi/flasktaskr
